### ISSUE TITLE
"Untitled document" do not sync

### ISSUE THREAD

**Issue by gmakstutis** [weichenw/obsidian-hypothesis-plugin#31]
I'm finding that there are some web pages that either do not have a title defined or that the title does not get picked up by Hypothes.is. In Hypothes.is these get titled as "Untitled document" and annoations/highlights do not get synced to Obsidian.

Here is an example:
![CleanShot 2022-01-20 at 13 48 25](https://user-images.githubusercontent.com/26612028/150350967-8cfedf96-4b45-4c62-9bf4-419ed8dd1bc7.png)

**Comment by benytzlich** [comment]
I have the same issue with annotated PDFs which are saved locally on PC. they seem not to be transferred to obsidian ???!

**Comment by weichenw** [comment]
> I have the same issue with annotated PDFs which are saved locally on PC. they seem not to be transferred to obsidian ???!

Clearly stated in the README...
Sync web article highlights/annotations and the caveat is not tested/supported on PDF.

**Comment by weichenw** [comment]
> I'm finding that there are some web pages that either do not have a title defined or that the title does not get picked up by Hypothes.is. In Hypothes.is these get titled as "Untitled document" and annoations/highlights do not get synced to Obsidian.
> 
> Here is an example: ![CleanShot 2022-01-20 at 13 48 25](https://user-images.githubusercontent.com/26612028/150350967-8cfedf96-4b45-4c62-9bf4-419ed8dd1bc7.png)

Unfortunately, the hypothesis store those articles with randomly generated id. Unless obsidian creates the files using the hypothesis id, it is going to be tricky. Nevertheless, I will look into it.

**Comment by gmakstutis** [comment]
@benytzlich If you are interested in using Hypothes.is to annotate PDFs, you might look at using the [Annotator Plugin](https://github.com/elias-sundqvist/obsidian-annotator) for Obsidian. However, I think it is using a locally modified version of Hypothes.is.

**Comment by phgn0** [comment]
Generating files for "Untitled document" pages should be fixed with https://github.com/weichenw/obsidian-hypothesis-plugin/pull/35.

> Unfortunately, the hypothesis store those articles with randomly generated id. Unless obsidian creates the files using the hypothesis id, it is going to be tricky.

Why will it be tricky? Shouldn't the page URL still be the same regardless of the metadata title?

**Comment by woodae99** [comment]
> @benytzlich If you are interested in using Hypothes.is to annotate PDFs, you might look at using the [Annotator Plugin](https://github.com/elias-sundqvist/obsidian-annotator) for Obsidian. However, I think it is using a locally modified version of Hypothes.is.

Hey all. 
Again, thanks for the plugin!
I wanted to ask about this, too. With hypothesis on local pdf's the annotations sync to the hypothesis web page with all my other notes, but don't sync to obsidian (as pointed out in your limitations bit) and then the annotator plugin has the opposite problem in that whatever you annotate with it does not show up online.

I work a lot with research students. In a scenario where I mark up a pdf offline, I can email them the pdf, and when they open it in a local browser window, my hypothesis notes show up, and they can add their own notes too, and so on with the collaboration. 
So off a bunch of disparate local copies, hypothesis manages to know which document it's looking at and bring in the notes. If I want to get those annotations from the web, I can use the export function (https://web.hypothes.is/help/how-do-i-export-my-annotations/) and then copy / paste into MD files, which is a workaround, but a bit of a pain, esp when there are updates all the time.

Is it possible to have your plugin pull those accumulated annotations out, too even if hypothesis calls it "local file"?
What I do to keep track of what's what, is put the bibliography info into a hypothesis page note, find of in the place of a file name, so that I can keep track of which paper we're talking about then all the other notes are collated with it.

Thanks for bearing with me!
C
